/* AC-GA-EXP · expense seed（原 HTML 硬寫資料遷移；已核對總額一致，勿手改）*/
window.EXP_SEED={
"categories": {
"electric": {
"icon": "⚡",
"label": "Electricity 電費",
"type": "utility"
},
"water": {
"icon": "🚿",
"label": "City Water 城市水費",
"type": "utility"
},
"security": {
"icon": "🛡️",
"label": "Security 保安費",
"type": "service"
},
"drinkwater": {
"icon": "💧",
"label": "Drinking Water 飲用水",
"type": "service"
},
"appform": {
"icon": "📝",
"label": "Application Form 表格印刷",
"type": "purchase"
},
"paper": {
"icon": "📄",
"label": "A4/A3 Paper 影印紙",
"type": "purchase"
},
"mask": {
"icon": "😷",
"label": "Face Mask 口罩",
"type": "purchase"
},
"toilet": {
"icon": "🧻",
"label": "Toilet Paper 廁紙",
"type": "purchase"
},
"cleaning": {
"icon": "🧹",
"label": "Cleaning 清潔用品",
"type": "purchase"
},
"stationery": {
"icon": "✏️",
"label": "Stationery 文具",
"type": "purchase"
},
"other": {
"icon": "📦",
"label": "Others 其他雜項",
"type": "purchase"
},
"kitchen": {
"icon": "🍳",
"label": "Kitchen & Food 廚房食材",
"type": "purchase"
},
"banner": {
"icon": "🪧",
"label": "Banner / Sign 招牌標識",
"type": "purchase"
},
"gasoline": {
"icon": "⛽",
"label": "Gasoline 汽油",
"type": "purchase"
},
"guest": {
"icon": "🍽️",
"label": "Guest / Auditor 接待餐飲",
"type": "purchase"
},
"gas": {
"icon": "🔥",
"label": "Gas 煤氣",
"type": "purchase"
},
"clinic": {
"icon": "🏥",
"label": "Clinic 診所藥費",
"type": "service"
},
"donation": {
"icon": "🎁",
"label": "Donation 捐贈",
"type": "purchase"
},
"biztrip": {
"icon": "✈️",
"label": "Business Trip 出差",
"type": "purchase"
},
"fireext": {
"icon": "🧯",
"label": "Fire Extinguisher 滅火器",
"type": "purchase"
},
"training": {
"icon": "📚",
"label": "Training 培訓",
"type": "purchase"
},
"decoration": {
"icon": "🎨",
"label": "Decoration 辦公室裝飾",
"type": "purchase"
},
"independent": {
"icon": "🔧",
"label": "Independent 獨立採購",
"type": "purchase"
},
"covid": {
"icon": "🧪",
"label": "Covid Test Kit",
"type": "purchase"
}
},
"transactions": [
{
"category": "electric",
"categoryLabel": "Electricity 電費",
"icon": "⚡",
"date": "2026-01-01",
"item": "工廠 Factory",
"spec": "",
"qty": 0.0,
"unit": "",
"supplier": "",
"amount": 3892.8,
"consumption": 24638.0,
"consUnit": "KW",
"purpose": "",
"sourceModule": "seed",
"dept": "工廠 Factory"
},
{
"category": "electric",
"categoryLabel": "Electricity 電費",
"icon": "⚡",
"date": "2026-01-01",
"item": "外籍宿舍 Expat S.H.",
"spec": "",
"qty": 0.0,
"unit": "",
"supplier": "",
"amount": 503.15,
"consumption": 2757.0,
"consUnit": "KW",
"purpose": "",
"sourceModule": "seed",
"dept": "外籍宿舍 Expat S.H."
},
{
"category": "electric",
"categoryLabel": "Electricity 電費",
"icon": "⚡",
"date": "2026-01-01",
"item": "本地宿舍 Local S.H.",
"spec": "",
"qty": 0.0,
"unit": "",
"supplier": "",
"amount": 119.9,
"consumption": 657.0,
"consUnit": "KW",
"purpose": "",
"sourceModule": "seed",
"dept": "本地宿舍 Local S.H."
},
{
"category": "electric",
"categoryLabel": "Electricity 電費",
"icon": "⚡",
"date": "2026-02-01",
"item": "工廠 Factory",
"spec": "",
"qty": 0.0,
"unit": "",
"supplier": "",
"amount": 4735.42,
"consumption": 29971.0,
"consUnit": "KW",
"purpose": "",
"sourceModule": "seed",
"dept": "工廠 Factory"
},
{
"category": "electric",
"categoryLabel": "Electricity 電費",
"icon": "⚡",
"date": "2026-02-01",
"item": "外籍宿舍 Expat S.H.",
"spec": "",
"qty": 0.0,
"unit": "",
"supplier": "",
"amount": 525.78,
"consumption": 2881.0,
"consUnit": "KW",
"purpose": "",
"sourceModule": "seed",
"dept": "外籍宿舍 Expat S.H."
},
{
"category": "electric",
"categoryLabel": "Electricity 電費",
"icon": "⚡",
"date": "2026-02-01",
"item": "本地宿舍 Local S.H.",
"spec": "",
"qty": 0.0,
"unit": "",
"supplier": "",
"amount": 153.3,
"consumption": 840.0,
"consUnit": "KW",
"purpose": "",
"sourceModule": "seed",
"dept": "本地宿舍 Local S.H."
},
{
"category": "water",
"categoryLabel": "City Water 城市水費",
"icon": "🚿",
"date": "2026-01-01",
"item": "工廠 Factory",
"spec": "",
"qty": 0.0,
"unit": "",
"supplier": "",
"amount": 287.13,
"consumption": 514.0,
"consUnit": "m³",
"purpose": "",
"sourceModule": "seed",
"dept": "工廠 Factory"
},
{
"category": "water",
"categoryLabel": "City Water 城市水費",
"icon": "🚿",
"date": "2026-01-01",
"item": "外籍宿舍 Expat S.H.",
"spec": "",
"qty": 0.0,
"unit": "",
"supplier": "",
"amount": 1.15,
"consumption": 3.0,
"consUnit": "m³",
"purpose": "",
"sourceModule": "seed",
"dept": "外籍宿舍 Expat S.H."
},
{
"category": "water",
"categoryLabel": "City Water 城市水費",
"icon": "🚿",
"date": "2026-01-01",
"item": "本地宿舍 Local S.H.",
"spec": "",
"qty": 0.0,
"unit": "",
"supplier": "",
"amount": 29.5,
"consumption": 67.0,
"consUnit": "m³",
"purpose": "",
"sourceModule": "seed",
"dept": "本地宿舍 Local S.H."
},
{
"category": "water",
"categoryLabel": "City Water 城市水費",
"icon": "🚿",
"date": "2026-02-01",
"item": "工廠 Factory",
"spec": "",
"qty": 0.0,
"unit": "",
"supplier": "",
"amount": 322.13,
"consumption": 570.0,
"consUnit": "m³",
"purpose": "",
"sourceModule": "seed",
"dept": "工廠 Factory"
},
{
"category": "water",
"categoryLabel": "City Water 城市水費",
"icon": "🚿",
"date": "2026-02-01",
"item": "外籍宿舍 Expat S.H.",
"spec": "",
"qty": 0.0,
"unit": "",
"supplier": "",
"amount": 1.15,
"consumption": 3.0,
"consUnit": "m³",
"purpose": "",
"sourceModule": "seed",
"dept": "外籍宿舍 Expat S.H."
},
{
"category": "water",
"categoryLabel": "City Water 城市水費",
"icon": "🚿",
"date": "2026-02-01",
"item": "本地宿舍 Local S.H.",
"spec": "",
"qty": 0.0,
"unit": "",
"supplier": "",
"amount": 33.5,
"consumption": 67.0,
"consUnit": "m³",
"purpose": "",
"sourceModule": "seed",
"dept": "本地宿舍 Local S.H."
},
{
"category": "security",
"categoryLabel": "Security 保安費",
"icon": "🛡️",
"date": "2026-01-01",
"item": "廠房保安 Factory Security",
"spec": "",
"qty": 1.0,
"unit": "月",
"supplier": "",
"amount": 2970.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "Staff house 2PPLs",
"sourceModule": "seed",
"dept": ""
},
{
"category": "security",
"categoryLabel": "Security 保安費",
"icon": "🛡️",
"date": "2026-01-01",
"item": "宿舍保安 Staff House Security",
"spec": "",
"qty": 1.0,
"unit": "月",
"supplier": "",
"amount": 660.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "New staff house",
"sourceModule": "seed",
"dept": ""
},
{
"category": "security",
"categoryLabel": "Security 保安費",
"icon": "🛡️",
"date": "2026-02-01",
"item": "廠房保安 Factory Security",
"spec": "",
"qty": 1.0,
"unit": "月",
"supplier": "",
"amount": 2970.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "Staff house 2PPLs",
"sourceModule": "seed",
"dept": ""
},
{
"category": "security",
"categoryLabel": "Security 保安費",
"icon": "🛡️",
"date": "2026-02-01",
"item": "宿舍保安 Staff House Security",
"spec": "",
"qty": 1.0,
"unit": "月",
"supplier": "",
"amount": 660.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "New staff house",
"sourceModule": "seed",
"dept": ""
},
{
"category": "drinkwater",
"categoryLabel": "Drinking Water 飲用水",
"icon": "💧",
"date": "2026-01-01",
"item": "Drinking water Shop 1",
"spec": "",
"qty": 1.0,
"unit": "month",
"supplier": "",
"amount": 455.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "Factory drinking water",
"sourceModule": "seed",
"dept": ""
},
{
"category": "appform",
"categoryLabel": "Application Form 表格印刷",
"icon": "📝",
"date": "2026-01-03",
"item": "Copy form (QC form)",
"spec": "A4",
"qty": 3200.0,
"unit": "pcs",
"supplier": "Chheng Hort",
"amount": 120.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "QC & QA dept",
"sourceModule": "seed",
"dept": ""
},
{
"category": "appform",
"categoryLabel": "Application Form 表格印刷",
"icon": "📝",
"date": "2026-01-28",
"item": "Stock bin card",
"spec": "—",
"qty": 1500.0,
"unit": "pcs",
"supplier": "Chheng Hort",
"amount": 225.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "Warehouse Trim",
"sourceModule": "seed",
"dept": ""
},
{
"category": "appform",
"categoryLabel": "Application Form 表格印刷",
"icon": "📝",
"date": "2026-02-03",
"item": "Fabric report table form",
"spec": "—",
"qty": 2000.0,
"unit": "pcs",
"supplier": "Chheng Hort",
"amount": 60.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "Cutting use",
"sourceModule": "seed",
"dept": ""
},
{
"category": "appform",
"categoryLabel": "Application Form 表格印刷",
"icon": "📝",
"date": "2026-02-26",
"item": "Trim requisition form 3-layer",
"spec": "3ជាន់",
"qty": 20.0,
"unit": "Box",
"supplier": "Chheng Hort",
"amount": 60.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "Warehouse Trim",
"sourceModule": "seed",
"dept": ""
},
{
"category": "appform",
"categoryLabel": "Application Form 表格印刷",
"icon": "📝",
"date": "2026-02-28",
"item": "Copy form (Cutting)",
"spec": "A4",
"qty": 3200.0,
"unit": "pcs",
"supplier": "Chheng Hort",
"amount": 96.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "Cutting use",
"sourceModule": "seed",
"dept": ""
},
{
"category": "paper",
"categoryLabel": "A4/A3 Paper 影印紙",
"icon": "📄",
"date": "2026-01-03",
"item": "A4 paper",
"spec": "70GSM 500sh/5pcs",
"qty": 8.0,
"unit": "ctn",
"supplier": "Various",
"amount": 120.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For stock",
"sourceModule": "seed",
"dept": ""
},
{
"category": "paper",
"categoryLabel": "A4/A3 Paper 影印紙",
"icon": "📄",
"date": "2026-02-02",
"item": "A4 paper",
"spec": "70GSM 500sh/5pcs",
"qty": 10.0,
"unit": "ctn",
"supplier": "Various",
"amount": 150.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For stock",
"sourceModule": "seed",
"dept": ""
},
{
"category": "mask",
"categoryLabel": "Face Mask 口罩",
"icon": "😷",
"date": "2026-01-02",
"item": "Face Mask",
"spec": "50pcs/box",
"qty": 45.0,
"unit": "box",
"supplier": "Various",
"amount": 45.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For stock",
"sourceModule": "seed",
"dept": ""
},
{
"category": "mask",
"categoryLabel": "Face Mask 口罩",
"icon": "😷",
"date": "2026-02-02",
"item": "Face Mask",
"spec": "50pcs/box",
"qty": 50.0,
"unit": "box",
"supplier": "Various",
"amount": 50.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For stock",
"sourceModule": "seed",
"dept": ""
},
{
"category": "toilet",
"categoryLabel": "Toilet Paper 廁紙",
"icon": "🧻",
"date": "2026-02-02",
"item": "Toilet paper",
"spec": "120pcs/ctn",
"qty": 1.0,
"unit": "ctn",
"supplier": "Various",
"amount": 22.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "—",
"sourceModule": "seed",
"dept": ""
},
{
"category": "cleaning",
"categoryLabel": "Cleaning 清潔用品",
"icon": "🧹",
"date": "2026-01-02",
"item": "Hand Wash",
"spec": "26L/tonk",
"qty": 1.0,
"unit": "tonk",
"supplier": "Various",
"amount": 15.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "Cleaner & Security",
"sourceModule": "seed",
"dept": ""
},
{
"category": "cleaning",
"categoryLabel": "Cleaning 清潔用品",
"icon": "🧹",
"date": "2026-01-02",
"item": "Bleach",
"spec": "2500ml/btl",
"qty": 1.0,
"unit": "btl",
"supplier": "Various",
"amount": 3.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "Production",
"sourceModule": "seed",
"dept": ""
},
{
"category": "cleaning",
"categoryLabel": "Cleaning 清潔用品",
"icon": "🧹",
"date": "2026-01-02",
"item": "Insect Killer",
"spec": "600ml/btl",
"qty": 5.0,
"unit": "btl",
"supplier": "Various",
"amount": 15.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For stock",
"sourceModule": "seed",
"dept": ""
},
{
"category": "cleaning",
"categoryLabel": "Cleaning 清潔用品",
"icon": "🧹",
"date": "2026-01-02",
"item": "Toilet bleach",
"spec": "900ml/btl",
"qty": 4.0,
"unit": "btl",
"supplier": "Various",
"amount": 7.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For cleaner",
"sourceModule": "seed",
"dept": ""
},
{
"category": "cleaning",
"categoryLabel": "Cleaning 清潔用品",
"icon": "🧹",
"date": "2026-01-02",
"item": "Plastic glove",
"spec": "L",
"qty": 3.0,
"unit": "pair",
"supplier": "Various",
"amount": 4.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For cleaner",
"sourceModule": "seed",
"dept": ""
},
{
"category": "cleaning",
"categoryLabel": "Cleaning 清潔用品",
"icon": "🧹",
"date": "2026-01-02",
"item": "Fresher Spray",
"spec": "520ml/btl",
"qty": 1.0,
"unit": "btl",
"supplier": "Various",
"amount": 2.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For GA",
"sourceModule": "seed",
"dept": ""
},
{
"category": "cleaning",
"categoryLabel": "Cleaning 清潔用品",
"icon": "🧹",
"date": "2026-01-02",
"item": "Plastic broom",
"spec": "—",
"qty": 1.0,
"unit": "pcs",
"supplier": "Various",
"amount": 2.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For cleaner",
"sourceModule": "seed",
"dept": ""
},
{
"category": "cleaning",
"categoryLabel": "Cleaning 清潔用品",
"icon": "🧹",
"date": "2026-01-02",
"item": "Big polybag",
"spec": "70×120 25kg",
"qty": 2.0,
"unit": "sack",
"supplier": "Various",
"amount": 62.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Cleaner",
"sourceModule": "seed",
"dept": ""
},
{
"category": "cleaning",
"categoryLabel": "Cleaning 清潔用品",
"icon": "🧹",
"date": "2026-01-02",
"item": "Soap Powder",
"spec": "4kg/bag 16kg",
"qty": 2.0,
"unit": "ctn",
"supplier": "Various",
"amount": 44.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For stock",
"sourceModule": "seed",
"dept": ""
},
{
"category": "cleaning",
"categoryLabel": "Cleaning 清潔用品",
"icon": "🧹",
"date": "2026-01-03",
"item": "Broom",
"spec": "—",
"qty": 4.0,
"unit": "pcs",
"supplier": "Various",
"amount": 7.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For cleaner",
"sourceModule": "seed",
"dept": ""
},
{
"category": "cleaning",
"categoryLabel": "Cleaning 清潔用品",
"icon": "🧹",
"date": "2026-01-17",
"item": "Liquid soap clothes",
"spec": "—",
"qty": 1.0,
"unit": "btl",
"supplier": "Various",
"amount": 7.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "Staff house",
"sourceModule": "seed",
"dept": ""
},
{
"category": "cleaning",
"categoryLabel": "Cleaning 清潔用品",
"icon": "🧹",
"date": "2026-02-02",
"item": "Big polybag",
"spec": "70×120 25kg",
"qty": 2.0,
"unit": "sack",
"supplier": "Various",
"amount": 62.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Cleaner",
"sourceModule": "seed",
"dept": ""
},
{
"category": "cleaning",
"categoryLabel": "Cleaning 清潔用品",
"icon": "🧹",
"date": "2026-02-02",
"item": "Soap Powder",
"spec": "4kg/bag 16kg",
"qty": 1.0,
"unit": "ctn",
"supplier": "Various",
"amount": 23.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For stock",
"sourceModule": "seed",
"dept": ""
},
{
"category": "cleaning",
"categoryLabel": "Cleaning 清潔用品",
"icon": "🧹",
"date": "2026-02-02",
"item": "Hand Wash",
"spec": "26L/tonk",
"qty": 1.0,
"unit": "tonk",
"supplier": "Various",
"amount": 15.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For stock",
"sourceModule": "seed",
"dept": ""
},
{
"category": "cleaning",
"categoryLabel": "Cleaning 清潔用品",
"icon": "🧹",
"date": "2026-02-02",
"item": "Insect Killer",
"spec": "600ml/btl",
"qty": 8.0,
"unit": "btl",
"supplier": "Various",
"amount": 24.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For stock",
"sourceModule": "seed",
"dept": ""
},
{
"category": "cleaning",
"categoryLabel": "Cleaning 清潔用品",
"icon": "🧹",
"date": "2026-02-02",
"item": "Toilet bleach",
"spec": "900ml/btl",
"qty": 2.0,
"unit": "btl",
"supplier": "Various",
"amount": 3.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Cleaner",
"sourceModule": "seed",
"dept": ""
},
{
"category": "stationery",
"categoryLabel": "Stationery 文具",
"icon": "✏️",
"date": "2026-01-02",
"item": "Brown envelop",
"spec": "50pcs/pack",
"qty": 1.0,
"unit": "pack",
"supplier": "Ly heng",
"amount": 3.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For stock",
"sourceModule": "seed",
"dept": ""
},
{
"category": "stationery",
"categoryLabel": "Stationery 文具",
"icon": "✏️",
"date": "2026-01-02",
"item": "Pencil",
"spec": "12pcs/box",
"qty": 1.0,
"unit": "box",
"supplier": "Ly heng",
"amount": 1.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For stock",
"sourceModule": "seed",
"dept": ""
},
{
"category": "stationery",
"categoryLabel": "Stationery 文具",
"icon": "✏️",
"date": "2026-01-02",
"item": "Red pen",
"spec": "—",
"qty": 5.0,
"unit": "pcs",
"supplier": "Ly heng",
"amount": 1.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For stock",
"sourceModule": "seed",
"dept": ""
},
{
"category": "stationery",
"categoryLabel": "Stationery 文具",
"icon": "✏️",
"date": "2026-01-02",
"item": "High Lighter",
"spec": "4.00mm",
"qty": 10.0,
"unit": "pcs",
"supplier": "Ly heng",
"amount": 5.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For stock",
"sourceModule": "seed",
"dept": ""
},
{
"category": "stationery",
"categoryLabel": "Stationery 文具",
"icon": "✏️",
"date": "2026-01-02",
"item": "Blue pen",
"spec": "50pcs/box",
"qty": 1.0,
"unit": "box",
"supplier": "Ly heng",
"amount": 4.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For stock",
"sourceModule": "seed",
"dept": ""
},
{
"category": "stationery",
"categoryLabel": "Stationery 文具",
"icon": "✏️",
"date": "2026-01-03",
"item": "Yellow tape",
"spec": "12pcs/roll",
"qty": 3.0,
"unit": "roll",
"supplier": "Ly heng",
"amount": 19.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For stock",
"sourceModule": "seed",
"dept": ""
},
{
"category": "stationery",
"categoryLabel": "Stationery 文具",
"icon": "✏️",
"date": "2026-01-03",
"item": "Note book",
"spec": "200sheet",
"qty": 5.0,
"unit": "pcs",
"supplier": "Ly heng",
"amount": 3.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For stock",
"sourceModule": "seed",
"dept": ""
},
{
"category": "stationery",
"categoryLabel": "Stationery 文具",
"icon": "✏️",
"date": "2026-01-03",
"item": "Big book",
"spec": "604sheet",
"qty": 2.0,
"unit": "pcs",
"supplier": "Ly heng",
"amount": 2.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For stock",
"sourceModule": "seed",
"dept": ""
},
{
"category": "stationery",
"categoryLabel": "Stationery 文具",
"icon": "✏️",
"date": "2026-01-03",
"item": "Small Clear tape",
"spec": "10pcs/roll",
"qty": 1.0,
"unit": "roll",
"supplier": "Ly heng",
"amount": 1.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For stock",
"sourceModule": "seed",
"dept": ""
},
{
"category": "stationery",
"categoryLabel": "Stationery 文具",
"icon": "✏️",
"date": "2026-02-02",
"item": "Yellow tape",
"spec": "12pcs/box",
"qty": 3.0,
"unit": "roll",
"supplier": "Ly heng",
"amount": 19.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For stock",
"sourceModule": "seed",
"dept": ""
},
{
"category": "stationery",
"categoryLabel": "Stationery 文具",
"icon": "✏️",
"date": "2026-02-02",
"item": "Binder clip 51mm",
"spec": "12pcs/box",
"qty": 3.0,
"unit": "box",
"supplier": "Ly heng",
"amount": 4.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Office",
"sourceModule": "seed",
"dept": ""
},
{
"category": "stationery",
"categoryLabel": "Stationery 文具",
"icon": "✏️",
"date": "2026-02-02",
"item": "Double tape",
"spec": "24pcs/roll",
"qty": 1.0,
"unit": "roll",
"supplier": "Ly heng",
"amount": 3.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For stock",
"sourceModule": "seed",
"dept": ""
},
{
"category": "stationery",
"categoryLabel": "Stationery 文具",
"icon": "✏️",
"date": "2026-02-02",
"item": "Small Clear tape",
"spec": "10pcs/roll",
"qty": 2.0,
"unit": "roll",
"supplier": "Ly heng",
"amount": 3.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For stock",
"sourceModule": "seed",
"dept": ""
},
{
"category": "stationery",
"categoryLabel": "Stationery 文具",
"icon": "✏️",
"date": "2026-02-02",
"item": "Blue pen",
"spec": "50pcs/box",
"qty": 1.0,
"unit": "box",
"supplier": "Ly heng",
"amount": 4.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For stock",
"sourceModule": "seed",
"dept": ""
},
{
"category": "stationery",
"categoryLabel": "Stationery 文具",
"icon": "✏️",
"date": "2026-02-02",
"item": "Correction pen",
"spec": "12pcs/box",
"qty": 1.0,
"unit": "box",
"supplier": "Ly heng",
"amount": 3.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "Production",
"sourceModule": "seed",
"dept": ""
},
{
"category": "stationery",
"categoryLabel": "Stationery 文具",
"icon": "✏️",
"date": "2026-02-02",
"item": "Permanent marker",
"spec": "12pcs/box",
"qty": 1.0,
"unit": "box",
"supplier": "Ly heng",
"amount": 4.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "Production",
"sourceModule": "seed",
"dept": ""
},
{
"category": "stationery",
"categoryLabel": "Stationery 文具",
"icon": "✏️",
"date": "2026-02-02",
"item": "Binder clip 25mm",
"spec": "12pcs/box",
"qty": 4.0,
"unit": "box",
"supplier": "Ly heng",
"amount": 2.4,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Office",
"sourceModule": "seed",
"dept": ""
},
{
"category": "stationery",
"categoryLabel": "Stationery 文具",
"icon": "✏️",
"date": "2026-02-02",
"item": "High Lighter",
"spec": "4.0mm",
"qty": 10.0,
"unit": "pcs",
"supplier": "Ly heng",
"amount": 5.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For stock",
"sourceModule": "seed",
"dept": ""
},
{
"category": "stationery",
"categoryLabel": "Stationery 文具",
"icon": "✏️",
"date": "2026-02-02",
"item": "Tailor Chalk",
"spec": "12pcs/pack",
"qty": 1.0,
"unit": "pack",
"supplier": "Ly heng",
"amount": 1.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "Production",
"sourceModule": "seed",
"dept": ""
},
{
"category": "stationery",
"categoryLabel": "Stationery 文具",
"icon": "✏️",
"date": "2026-02-02",
"item": "Red pen",
"spec": "50pcs/box",
"qty": 5.0,
"unit": "pcs",
"supplier": "Ly heng",
"amount": 1.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For stock",
"sourceModule": "seed",
"dept": ""
},
{
"category": "stationery",
"categoryLabel": "Stationery 文具",
"icon": "✏️",
"date": "2026-02-02",
"item": "Battery AA",
"spec": "—",
"qty": 2.0,
"unit": "pack",
"supplier": "Ly heng",
"amount": 2.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Office",
"sourceModule": "seed",
"dept": ""
},
{
"category": "stationery",
"categoryLabel": "Stationery 文具",
"icon": "✏️",
"date": "2026-02-02",
"item": "Battery AAA",
"spec": "—",
"qty": 1.0,
"unit": "pack",
"supplier": "Ly heng",
"amount": 1.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Office",
"sourceModule": "seed",
"dept": ""
},
{
"category": "stationery",
"categoryLabel": "Stationery 文具",
"icon": "✏️",
"date": "2026-02-02",
"item": "Big book",
"spec": "244sheet",
"qty": 5.0,
"unit": "book",
"supplier": "Ly heng",
"amount": 10.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "Production",
"sourceModule": "seed",
"dept": ""
},
{
"category": "stationery",
"categoryLabel": "Stationery 文具",
"icon": "✏️",
"date": "2026-02-02",
"item": "Note book",
"spec": "200sheet",
"qty": 3.0,
"unit": "book",
"supplier": "Ly heng",
"amount": 1.8,
"consumption": 0.0,
"consUnit": "",
"purpose": "Production",
"sourceModule": "seed",
"dept": ""
},
{
"category": "other",
"categoryLabel": "Others 其他雜項",
"icon": "📦",
"date": "2026-01-02",
"item": "String folder",
"spec": "A4 10pcs/pack",
"qty": 1.0,
"unit": "pack",
"supplier": "Ly heng",
"amount": 5.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For HR",
"sourceModule": "seed",
"dept": ""
},
{
"category": "other",
"categoryLabel": "Others 其他雜項",
"icon": "📦",
"date": "2026-01-02",
"item": "Plastic clear sheet",
"spec": "100sheet/pcs",
"qty": 1.0,
"unit": "pcs",
"supplier": "Ly heng",
"amount": 2.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "Asst.Admin",
"sourceModule": "seed",
"dept": ""
},
{
"category": "other",
"categoryLabel": "Others 其他雜項",
"icon": "📦",
"date": "2026-01-02",
"item": "Clip board",
"spec": "A4",
"qty": 2.0,
"unit": "pcs",
"supplier": "Ly heng",
"amount": 2.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "Sewing L11",
"sourceModule": "seed",
"dept": ""
},
{
"category": "other",
"categoryLabel": "Others 其他雜項",
"icon": "📦",
"date": "2026-01-02",
"item": "Pentel Pencil",
"spec": "0.5",
"qty": 1.0,
"unit": "pcs",
"supplier": "Ly heng",
"amount": 1.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "Asst.Admin",
"sourceModule": "seed",
"dept": ""
},
{
"category": "other",
"categoryLabel": "Others 其他雜項",
"icon": "📦",
"date": "2026-01-02",
"item": "Clear plastic bag",
"spec": "5×8",
"qty": 1.0,
"unit": "kg",
"supplier": "Various",
"amount": 1.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "GA use",
"sourceModule": "seed",
"dept": ""
},
{
"category": "other",
"categoryLabel": "Others 其他雜項",
"icon": "📦",
"date": "2026-01-03",
"item": "Ink (stamp pad)",
"spec": "—",
"qty": 1.0,
"unit": "btl",
"supplier": "Ly heng",
"amount": 0.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "Asst.Admin",
"sourceModule": "seed",
"dept": ""
},
{
"category": "other",
"categoryLabel": "Others 其他雜項",
"icon": "📦",
"date": "2026-01-14",
"item": "Plastic bag 6×14",
"spec": "6×14",
"qty": 10.0,
"unit": "kg",
"supplier": "Various",
"amount": 20.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "Warehouse Trim",
"sourceModule": "seed",
"dept": ""
},
{
"category": "other",
"categoryLabel": "Others 其他雜項",
"icon": "📦",
"date": "2026-01-14",
"item": "Plastic bag 6×11",
"spec": "6×11",
"qty": 10.0,
"unit": "kg",
"supplier": "Various",
"amount": 20.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "Warehouse Trim",
"sourceModule": "seed",
"dept": ""
},
{
"category": "other",
"categoryLabel": "Others 其他雜項",
"icon": "📦",
"date": "2026-01-14",
"item": "Plastic bag 5×9",
"spec": "5×9",
"qty": 10.0,
"unit": "kg",
"supplier": "Various",
"amount": 20.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "Warehouse Trim",
"sourceModule": "seed",
"dept": ""
},
{
"category": "other",
"categoryLabel": "Others 其他雜項",
"icon": "📦",
"date": "2026-01-14",
"item": "Plastic bag 9×8",
"spec": "9×8",
"qty": 10.0,
"unit": "kg",
"supplier": "Various",
"amount": 20.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "Warehouse Trim",
"sourceModule": "seed",
"dept": ""
},
{
"category": "other",
"categoryLabel": "Others 其他雜項",
"icon": "📦",
"date": "2026-01-14",
"item": "Plastic bag 12×20",
"spec": "12×20",
"qty": 10.0,
"unit": "kg",
"supplier": "Various",
"amount": 20.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "Warehouse Trim",
"sourceModule": "seed",
"dept": ""
},
{
"category": "other",
"categoryLabel": "Others 其他雜項",
"icon": "📦",
"date": "2026-01-14",
"item": "Plastic bag 20×30",
"spec": "20×30",
"qty": 10.0,
"unit": "kg",
"supplier": "Various",
"amount": 20.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "Warehouse Trim",
"sourceModule": "seed",
"dept": ""
},
{
"category": "other",
"categoryLabel": "Others 其他雜項",
"icon": "📦",
"date": "2026-01-14",
"item": "Rubber band",
"spec": "—",
"qty": 5.0,
"unit": "kg",
"supplier": "Various",
"amount": 25.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "Warehouse Trim",
"sourceModule": "seed",
"dept": ""
},
{
"category": "other",
"categoryLabel": "Others 其他雜項",
"icon": "📦",
"date": "2026-01-16",
"item": "String folder",
"spec": "—",
"qty": 1.0,
"unit": "pcs",
"supplier": "Ly heng",
"amount": 5.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Account",
"sourceModule": "seed",
"dept": ""
},
{
"category": "other",
"categoryLabel": "Others 其他雜項",
"icon": "📦",
"date": "2026-01-16",
"item": "Fingertip moisturizer",
"spec": "—",
"qty": 1.0,
"unit": "pcs",
"supplier": "Ly heng",
"amount": 1.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Account",
"sourceModule": "seed",
"dept": ""
},
{
"category": "other",
"categoryLabel": "Others 其他雜項",
"icon": "📦",
"date": "2026-01-16",
"item": "Clear plastic folder",
"spec": "10pcs/pack",
"qty": 1.0,
"unit": "pack",
"supplier": "Ly heng",
"amount": 3.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Mr.Sam",
"sourceModule": "seed",
"dept": ""
},
{
"category": "other",
"categoryLabel": "Others 其他雜項",
"icon": "📦",
"date": "2026-01-17",
"item": "Traffic tape",
"spec": "—",
"qty": 2.0,
"unit": "pcs",
"supplier": "Various",
"amount": 7.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "Container sign",
"sourceModule": "seed",
"dept": ""
},
{
"category": "other",
"categoryLabel": "Others 其他雜項",
"icon": "📦",
"date": "2026-01-21",
"item": "Black soil",
"spec": "—",
"qty": 8.0,
"unit": "bag",
"supplier": "Various",
"amount": 8.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "Flower & Tree",
"sourceModule": "seed",
"dept": ""
},
{
"category": "other",
"categoryLabel": "Others 其他雜項",
"icon": "📦",
"date": "2026-01-28",
"item": "TGTV ID card (Hard)",
"spec": "100pcs/box",
"qty": 1.0,
"unit": "box",
"supplier": "H-T-P-P Royal",
"amount": 40.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For HR",
"sourceModule": "seed",
"dept": ""
},
{
"category": "other",
"categoryLabel": "Others 其他雜項",
"icon": "📦",
"date": "2026-01-28",
"item": "Mouse glue",
"spec": "12btl/ctn",
"qty": 1.0,
"unit": "ctn",
"supplier": "Various",
"amount": 15.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "Factory use",
"sourceModule": "seed",
"dept": ""
},
{
"category": "other",
"categoryLabel": "Others 其他雜項",
"icon": "📦",
"date": "2026-02-02",
"item": "Broom",
"spec": "—",
"qty": 12.0,
"unit": "pcs",
"supplier": "Various",
"amount": 21.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "Production",
"sourceModule": "seed",
"dept": ""
},
{
"category": "other",
"categoryLabel": "Others 其他雜項",
"icon": "📦",
"date": "2026-02-02",
"item": "Glue Stick",
"spec": "—",
"qty": 1.0,
"unit": "pcs",
"supplier": "Ly heng",
"amount": 1.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "Asst.Admin",
"sourceModule": "seed",
"dept": ""
},
{
"category": "other",
"categoryLabel": "Others 其他雜項",
"icon": "📦",
"date": "2026-02-02",
"item": "Clip board",
"spec": "A4",
"qty": 1.0,
"unit": "pcs",
"supplier": "Ly heng",
"amount": 1.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For QC",
"sourceModule": "seed",
"dept": ""
},
{
"category": "other",
"categoryLabel": "Others 其他雜項",
"icon": "📦",
"date": "2026-02-02",
"item": "Fruit",
"spec": "—",
"qty": 1.0,
"unit": "set",
"supplier": "Various",
"amount": 5.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "Sacred day",
"sourceModule": "seed",
"dept": ""
},
{
"category": "other",
"categoryLabel": "Others 其他雜項",
"icon": "📦",
"date": "2026-02-12",
"item": "Photo Frame A4",
"spec": "A4",
"qty": 2.0,
"unit": "pcs",
"supplier": "Ly heng",
"amount": 8.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "Certificate Warp",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-05",
"item": "Egg",
"spec": "—",
"qty": 10.0,
"unit": "pcs",
"supplier": "Various",
"amount": 1.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-05",
"item": "Sugar + Garlic",
"spec": "—",
"qty": 1.0,
"unit": "kg",
"supplier": "Various",
"amount": 0.75,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-05",
"item": "Bag",
"spec": "M",
"qty": 1.0,
"unit": "pcs",
"supplier": "Various",
"amount": 0.1,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-05",
"item": "Equal classic",
"spec": "100st",
"qty": 1.0,
"unit": "pcs",
"supplier": "Various",
"amount": 5.99,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-05",
"item": "Fish sauce",
"spec": "750ml",
"qty": 1.0,
"unit": "pcs",
"supplier": "Various",
"amount": 0.79,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-05",
"item": "Seasoning",
"spec": "400g",
"qty": 1.0,
"unit": "pcs",
"supplier": "Various",
"amount": 2.19,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-05",
"item": "Tomato pure",
"spec": "500g",
"qty": 1.0,
"unit": "pcs",
"supplier": "Various",
"amount": 1.59,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-05",
"item": "Soy sauce",
"spec": "1.97g",
"qty": 1.0,
"unit": "pcs",
"supplier": "Various",
"amount": 3.69,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-05",
"item": "Spices",
"spec": "5L",
"qty": 1.0,
"unit": "btl",
"supplier": "Various",
"amount": 8.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-05",
"item": "Spices",
"spec": "280g",
"qty": 1.0,
"unit": "pkg",
"supplier": "Various",
"amount": 2.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-05",
"item": "Spices",
"spec": "500ml",
"qty": 1.0,
"unit": "btl",
"supplier": "Various",
"amount": 1.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-05",
"item": "Spices",
"spec": "700g",
"qty": 2.0,
"unit": "pkg",
"supplier": "Various",
"amount": 3.3,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-05",
"item": "Spices",
"spec": "454g",
"qty": 1.0,
"unit": "pkg",
"supplier": "Various",
"amount": 3.8,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-05",
"item": "Oil",
"spec": "5L",
"qty": 1.0,
"unit": "btl",
"supplier": "Various",
"amount": 18.6,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-06",
"item": "Oyster sauce",
"spec": "—",
"qty": 1.0,
"unit": "btl",
"supplier": "Various",
"amount": 1.75,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-08",
"item": "Egg",
"spec": "—",
"qty": 5.0,
"unit": "pcs",
"supplier": "Various",
"amount": 0.75,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-08",
"item": "Sugar + Garlic",
"spec": "—",
"qty": 1.0,
"unit": "kg",
"supplier": "Various",
"amount": 0.75,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-12",
"item": "Egg",
"spec": "—",
"qty": 10.0,
"unit": "pcs",
"supplier": "Various",
"amount": 1.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-12",
"item": "Sugar + Garlic",
"spec": "—",
"qty": 10.0,
"unit": "kg",
"supplier": "Various",
"amount": 7.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-14",
"item": "Dish washing Liquid",
"spec": "—",
"qty": 1.0,
"unit": "ctn",
"supplier": "Various",
"amount": 15.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-15",
"item": "Egg",
"spec": "—",
"qty": 10.0,
"unit": "pcs",
"supplier": "Various",
"amount": 1.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-15",
"item": "Sugar + Garlic",
"spec": "—",
"qty": 1.0,
"unit": "kg",
"supplier": "Various",
"amount": 0.75,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-19",
"item": "Egg",
"spec": "—",
"qty": 10.0,
"unit": "pcs",
"supplier": "Various",
"amount": 1.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-19",
"item": "Sugar + Garlic",
"spec": "—",
"qty": 1.0,
"unit": "kg",
"supplier": "Various",
"amount": 0.75,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-22",
"item": "Egg",
"spec": "—",
"qty": 10.0,
"unit": "pcs",
"supplier": "Various",
"amount": 1.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-22",
"item": "Sugar + Garlic",
"spec": "—",
"qty": 1.0,
"unit": "kg",
"supplier": "Various",
"amount": 0.75,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-26",
"item": "Spices",
"spec": "5L",
"qty": 1.0,
"unit": "btl",
"supplier": "Various",
"amount": 8.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-26",
"item": "Spices",
"spec": "700g",
"qty": 1.0,
"unit": "pkg",
"supplier": "Various",
"amount": 1.65,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-26",
"item": "Spices",
"spec": "480ml",
"qty": 1.0,
"unit": "btl",
"supplier": "Various",
"amount": 3.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-26",
"item": "Spices",
"spec": "1kg",
"qty": 1.0,
"unit": "pkg",
"supplier": "Various",
"amount": 7.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-26",
"item": "Khnar soup powder",
"spec": "—",
"qty": 1.0,
"unit": "bag",
"supplier": "Various",
"amount": 3.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-26",
"item": "Oyster sauce",
"spec": "—",
"qty": 2.0,
"unit": "btl",
"supplier": "Various",
"amount": 4.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-26",
"item": "Seasoning",
"spec": "—",
"qty": 1.0,
"unit": "bag",
"supplier": "Various",
"amount": 3.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-26",
"item": "Egg",
"spec": "—",
"qty": 10.0,
"unit": "pcs",
"supplier": "Various",
"amount": 1.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-26",
"item": "Sugar + Garlic",
"spec": "—",
"qty": 1.0,
"unit": "kg",
"supplier": "Various",
"amount": 0.75,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-29",
"item": "Egg",
"spec": "—",
"qty": 10.0,
"unit": "pcs",
"supplier": "Various",
"amount": 1.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-01-29",
"item": "Sugar + Garlic",
"spec": "—",
"qty": 1.0,
"unit": "kg",
"supplier": "Various",
"amount": 0.75,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-02-02",
"item": "Egg",
"spec": "—",
"qty": 10.0,
"unit": "pcs",
"supplier": "Various",
"amount": 1.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-02-02",
"item": "Sugar + Garlic",
"spec": "—",
"qty": 1.0,
"unit": "kg",
"supplier": "Various",
"amount": 0.75,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-02-05",
"item": "Egg",
"spec": "—",
"qty": 10.0,
"unit": "pcs",
"supplier": "Various",
"amount": 1.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-02-05",
"item": "Sugar + Garlic",
"spec": "—",
"qty": 1.0,
"unit": "kg",
"supplier": "Various",
"amount": 0.75,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-02-06",
"item": "Food (staff meal)",
"spec": "—",
"qty": 3.0,
"unit": "PPL",
"supplier": "Various",
"amount": 7.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-02-09",
"item": "Egg",
"spec": "—",
"qty": 1.0,
"unit": "kg",
"supplier": "Various",
"amount": 0.75,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-02-09",
"item": "Sugar + Garlic",
"spec": "—",
"qty": 10.0,
"unit": "pcs",
"supplier": "Various",
"amount": 1.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-02-10",
"item": "Fish sauce",
"spec": "—",
"qty": 1.0,
"unit": "btl",
"supplier": "Various",
"amount": 1.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-02-12",
"item": "Egg",
"spec": "—",
"qty": 10.0,
"unit": "pcs",
"supplier": "Various",
"amount": 1.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-02-12",
"item": "Sugar + Garlic",
"spec": "—",
"qty": 1.0,
"unit": "kg",
"supplier": "Various",
"amount": 0.75,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-02-16",
"item": "Egg",
"spec": "—",
"qty": 10.0,
"unit": "pcs",
"supplier": "Various",
"amount": 1.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-02-16",
"item": "Sugar + Garlic",
"spec": "—",
"qty": 1.0,
"unit": "kg",
"supplier": "Various",
"amount": 0.75,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-02-19",
"item": "Egg",
"spec": "—",
"qty": 10.0,
"unit": "pcs",
"supplier": "Various",
"amount": 1.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-02-19",
"item": "Sugar + Garlic",
"spec": "—",
"qty": 1.0,
"unit": "kg",
"supplier": "Various",
"amount": 0.75,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-02-23",
"item": "Egg",
"spec": "—",
"qty": 10.0,
"unit": "pcs",
"supplier": "Various",
"amount": 1.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-02-23",
"item": "Sugar + Garlic",
"spec": "—",
"qty": 1.0,
"unit": "kg",
"supplier": "Various",
"amount": 0.75,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-02-24",
"item": "Oyster sauce",
"spec": "700g",
"qty": 1.0,
"unit": "pcs",
"supplier": "Various",
"amount": 2.49,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-02-24",
"item": "Fish sauce",
"spec": "750ml",
"qty": 1.0,
"unit": "pcs",
"supplier": "Various",
"amount": 0.79,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-02-24",
"item": "Rati chicken powder",
"spec": "400g",
"qty": 1.0,
"unit": "pcs",
"supplier": "Various",
"amount": 1.39,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-02-24",
"item": "Bag",
"spec": "xs",
"qty": 1.0,
"unit": "pcs",
"supplier": "Various",
"amount": 0.1,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-02-24",
"item": "Spices",
"spec": "454g",
"qty": 1.0,
"unit": "pkg",
"supplier": "Various",
"amount": 3.8,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-02-24",
"item": "Spices",
"spec": "1.9L",
"qty": 1.0,
"unit": "btl",
"supplier": "Various",
"amount": 3.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-02-24",
"item": "Spices",
"spec": "5L",
"qty": 1.0,
"unit": "btl",
"supplier": "Various",
"amount": 8.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-02-26",
"item": "Egg",
"spec": "—",
"qty": 10.0,
"unit": "pcs",
"supplier": "Various",
"amount": 1.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-02-26",
"item": "Sugar + Garlic",
"spec": "—",
"qty": 1.0,
"unit": "kg",
"supplier": "Various",
"amount": 0.75,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-02-27",
"item": "Dish washing Liquid",
"spec": "4tonk/ctn",
"qty": 1.0,
"unit": "ctn",
"supplier": "Various",
"amount": 15.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-02-27",
"item": "Egg",
"spec": "1×10",
"qty": 1.0,
"unit": "—",
"supplier": "Various",
"amount": 2.2,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-02-27",
"item": "Oil",
"spec": "6×2L",
"qty": 2.0,
"unit": "btl",
"supplier": "Various",
"amount": 20.22,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-02-27",
"item": "Bag",
"spec": "1×1",
"qty": 1.0,
"unit": "pcs",
"supplier": "Various",
"amount": 0.1,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-02-28",
"item": "Bag",
"spec": "L",
"qty": 1.0,
"unit": "pcs",
"supplier": "Various",
"amount": 0.1,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-02-28",
"item": "Comfort Ultra Blue AK",
"spec": "800ml",
"qty": 1.0,
"unit": "pcs",
"supplier": "Various",
"amount": 3.79,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "kitchen",
"categoryLabel": "Kitchen & Food 廚房食材",
"icon": "🍳",
"date": "2026-02-28",
"item": "Rise Laundry Detergent",
"spec": "3L",
"qty": 1.0,
"unit": "pcs",
"supplier": "Various",
"amount": 6.29,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "banner",
"categoryLabel": "Banner / Sign 招牌標識",
"icon": "🪧",
"date": "2026-01-05",
"item": "No Smoking Sign",
"spec": "—",
"qty": 1.0,
"unit": "pcs",
"supplier": "Various",
"amount": 10.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Shop A",
"sourceModule": "seed",
"dept": ""
},
{
"category": "banner",
"categoryLabel": "Banner / Sign 招牌標識",
"icon": "🪧",
"date": "2026-01-28",
"item": "Print & Laminate",
"spec": "—",
"qty": 3.0,
"unit": "pcs",
"supplier": "Chheng Hort",
"amount": 4.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "Sign for Fire Ext.",
"sourceModule": "seed",
"dept": ""
},
{
"category": "gasoline",
"categoryLabel": "Gasoline 汽油",
"icon": "⛽",
"date": "2026-01-12",
"item": "Gasoline",
"spec": "—",
"qty": 4.28,
"unit": "L",
"supplier": "Various",
"amount": 3.745,
"consumption": 0.0,
"consUnit": "",
"purpose": "Motorcycle 1H-5117",
"sourceModule": "seed",
"dept": ""
},
{
"category": "gasoline",
"categoryLabel": "Gasoline 汽油",
"icon": "⛽",
"date": "2026-02-03",
"item": "Gasoline",
"spec": "—",
"qty": 4.0,
"unit": "L",
"supplier": "Various",
"amount": 3.75,
"consumption": 0.0,
"consUnit": "",
"purpose": "Motorcycle 1I-9681",
"sourceModule": "seed",
"dept": ""
},
{
"category": "gasoline",
"categoryLabel": "Gasoline 汽油",
"icon": "⛽",
"date": "2026-02-14",
"item": "Gasoline",
"spec": "—",
"qty": 2.5,
"unit": "L",
"supplier": "Various",
"amount": 2.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "Motorcycle 1I-0423",
"sourceModule": "seed",
"dept": ""
},
{
"category": "gasoline",
"categoryLabel": "Gasoline 汽油",
"icon": "⛽",
"date": "2026-02-14",
"item": "Gasoline",
"spec": "—",
"qty": 2.0,
"unit": "L",
"supplier": "Various",
"amount": 2.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "Motorcycle 1H-5117",
"sourceModule": "seed",
"dept": ""
},
{
"category": "guest",
"categoryLabel": "Guest / Auditor 接待餐飲",
"icon": "🍽️",
"date": "2026-01-08",
"item": "Food",
"spec": "—",
"qty": 1.0,
"unit": "—",
"supplier": "Various",
"amount": 15.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For GRS",
"sourceModule": "seed",
"dept": ""
},
{
"category": "guest",
"categoryLabel": "Guest / Auditor 接待餐飲",
"icon": "🍽️",
"date": "2026-01-08",
"item": "Food",
"spec": "—",
"qty": 1.0,
"unit": "—",
"supplier": "Various",
"amount": 7.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For GRS",
"sourceModule": "seed",
"dept": ""
},
{
"category": "guest",
"categoryLabel": "Guest / Auditor 接待餐飲",
"icon": "🍽️",
"date": "2026-01-08",
"item": "Food",
"spec": "—",
"qty": 2.0,
"unit": "—",
"supplier": "Various",
"amount": 7.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For GRS",
"sourceModule": "seed",
"dept": ""
},
{
"category": "guest",
"categoryLabel": "Guest / Auditor 接待餐飲",
"icon": "🍽️",
"date": "2026-01-08",
"item": "Food",
"spec": "—",
"qty": 3.0,
"unit": "—",
"supplier": "Various",
"amount": 1.14,
"consumption": 0.0,
"consUnit": "",
"purpose": "For GRS",
"sourceModule": "seed",
"dept": ""
},
{
"category": "guest",
"categoryLabel": "Guest / Auditor 接待餐飲",
"icon": "🍽️",
"date": "2026-01-12",
"item": "Snack",
"spec": "—",
"qty": 1.0,
"unit": "—",
"supplier": "Lucky",
"amount": 2.625,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Customer",
"sourceModule": "seed",
"dept": ""
},
{
"category": "guest",
"categoryLabel": "Guest / Auditor 接待餐飲",
"icon": "🍽️",
"date": "2026-01-12",
"item": "Snack",
"spec": "—",
"qty": 1.0,
"unit": "—",
"supplier": "Lucky",
"amount": 2.625,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Customer",
"sourceModule": "seed",
"dept": ""
},
{
"category": "guest",
"categoryLabel": "Guest / Auditor 接待餐飲",
"icon": "🍽️",
"date": "2026-01-12",
"item": "Snack",
"spec": "—",
"qty": 1.0,
"unit": "—",
"supplier": "Lucky",
"amount": 2.85,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Customer",
"sourceModule": "seed",
"dept": ""
},
{
"category": "guest",
"categoryLabel": "Guest / Auditor 接待餐飲",
"icon": "🍽️",
"date": "2026-01-12",
"item": "Snack",
"spec": "—",
"qty": 1.0,
"unit": "—",
"supplier": "Lucky",
"amount": 1.325,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Customer",
"sourceModule": "seed",
"dept": ""
},
{
"category": "guest",
"categoryLabel": "Guest / Auditor 接待餐飲",
"icon": "🍽️",
"date": "2026-01-12",
"item": "Snack",
"spec": "—",
"qty": 1.0,
"unit": "—",
"supplier": "Lucky",
"amount": 1.225,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Customer",
"sourceModule": "seed",
"dept": ""
},
{
"category": "guest",
"categoryLabel": "Guest / Auditor 接待餐飲",
"icon": "🍽️",
"date": "2026-01-12",
"item": "Snack",
"spec": "—",
"qty": 1.0,
"unit": "—",
"supplier": "Lucky",
"amount": 1.15,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Customer",
"sourceModule": "seed",
"dept": ""
},
{
"category": "guest",
"categoryLabel": "Guest / Auditor 接待餐飲",
"icon": "🍽️",
"date": "2026-01-12",
"item": "Snack",
"spec": "—",
"qty": 2.0,
"unit": "—",
"supplier": "Lucky",
"amount": 1.8,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Customer",
"sourceModule": "seed",
"dept": ""
},
{
"category": "guest",
"categoryLabel": "Guest / Auditor 接待餐飲",
"icon": "🍽️",
"date": "2026-01-12",
"item": "Snack",
"spec": "—",
"qty": 1.0,
"unit": "—",
"supplier": "Lucky",
"amount": 0.1,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Customer",
"sourceModule": "seed",
"dept": ""
},
{
"category": "guest",
"categoryLabel": "Guest / Auditor 接待餐飲",
"icon": "🍽️",
"date": "2026-01-12",
"item": "Water",
"spec": "24btl",
"qty": 1.0,
"unit": "ctn",
"supplier": "Various",
"amount": 5.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Customer",
"sourceModule": "seed",
"dept": ""
},
{
"category": "guest",
"categoryLabel": "Guest / Auditor 接待餐飲",
"icon": "🍽️",
"date": "2026-01-13",
"item": "Food",
"spec": "—",
"qty": 1.0,
"unit": "—",
"supplier": "ខ្ចប់",
"amount": 16.2,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Warp",
"sourceModule": "seed",
"dept": ""
},
{
"category": "guest",
"categoryLabel": "Guest / Auditor 接待餐飲",
"icon": "🍽️",
"date": "2026-01-13",
"item": "Food",
"spec": "—",
"qty": 1.0,
"unit": "—",
"supplier": "ខ្ចប់",
"amount": 3.75,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Warp",
"sourceModule": "seed",
"dept": ""
},
{
"category": "guest",
"categoryLabel": "Guest / Auditor 接待餐飲",
"icon": "🍽️",
"date": "2026-01-13",
"item": "Food",
"spec": "—",
"qty": 1.0,
"unit": "—",
"supplier": "ខ្ចប់",
"amount": 2.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Warp",
"sourceModule": "seed",
"dept": ""
},
{
"category": "guest",
"categoryLabel": "Guest / Auditor 接待餐飲",
"icon": "🍽️",
"date": "2026-01-13",
"item": "Food",
"spec": "—",
"qty": 2.0,
"unit": "—",
"supplier": "ខ្ចប់",
"amount": 0.76,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Warp",
"sourceModule": "seed",
"dept": ""
},
{
"category": "guest",
"categoryLabel": "Guest / Auditor 接待餐飲",
"icon": "🍽️",
"date": "2026-01-14",
"item": "Food",
"spec": "—",
"qty": 1.0,
"unit": "—",
"supplier": "Various",
"amount": 3.75,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Warp",
"sourceModule": "seed",
"dept": ""
},
{
"category": "guest",
"categoryLabel": "Guest / Auditor 接待餐飲",
"icon": "🍽️",
"date": "2026-01-14",
"item": "Food",
"spec": "—",
"qty": 1.0,
"unit": "—",
"supplier": "Various",
"amount": 15.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Warp",
"sourceModule": "seed",
"dept": ""
},
{
"category": "guest",
"categoryLabel": "Guest / Auditor 接待餐飲",
"icon": "🍽️",
"date": "2026-01-14",
"item": "Food",
"spec": "—",
"qty": 1.0,
"unit": "—",
"supplier": "Various",
"amount": 2.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Warp",
"sourceModule": "seed",
"dept": ""
},
{
"category": "guest",
"categoryLabel": "Guest / Auditor 接待餐飲",
"icon": "🍽️",
"date": "2026-01-14",
"item": "Food",
"spec": "—",
"qty": 1.0,
"unit": "—",
"supplier": "Various",
"amount": 0.75,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Warp",
"sourceModule": "seed",
"dept": ""
},
{
"category": "guest",
"categoryLabel": "Guest / Auditor 接待餐飲",
"icon": "🍽️",
"date": "2026-01-15",
"item": "Food",
"spec": "—",
"qty": 3.0,
"unit": "—",
"supplier": "Chhne Meas",
"amount": 1.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Warp",
"sourceModule": "seed",
"dept": ""
},
{
"category": "guest",
"categoryLabel": "Guest / Auditor 接待餐飲",
"icon": "🍽️",
"date": "2026-01-15",
"item": "Food",
"spec": "—",
"qty": 2.0,
"unit": "—",
"supplier": "Chhne Meas",
"amount": 1.5,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Warp",
"sourceModule": "seed",
"dept": ""
},
{
"category": "guest",
"categoryLabel": "Guest / Auditor 接待餐飲",
"icon": "🍽️",
"date": "2026-01-15",
"item": "Food",
"spec": "—",
"qty": 1.0,
"unit": "—",
"supplier": "Chhne Meas",
"amount": 2.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Warp",
"sourceModule": "seed",
"dept": ""
},
{
"category": "guest",
"categoryLabel": "Guest / Auditor 接待餐飲",
"icon": "🍽️",
"date": "2026-01-15",
"item": "Food",
"spec": "—",
"qty": 1.0,
"unit": "—",
"supplier": "Chhne Meas",
"amount": 3.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Warp",
"sourceModule": "seed",
"dept": ""
},
{
"category": "guest",
"categoryLabel": "Guest / Auditor 接待餐飲",
"icon": "🍽️",
"date": "2026-01-15",
"item": "Food",
"spec": "—",
"qty": 1.0,
"unit": "—",
"supplier": "Chhne Meas",
"amount": 10.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Warp",
"sourceModule": "seed",
"dept": ""
},
{
"category": "guest",
"categoryLabel": "Guest / Auditor 接待餐飲",
"icon": "🍽️",
"date": "2026-01-15",
"item": "Food",
"spec": "—",
"qty": 2.0,
"unit": "—",
"supplier": "Chhne Meas",
"amount": 15.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Warp",
"sourceModule": "seed",
"dept": ""
},
{
"category": "guest",
"categoryLabel": "Guest / Auditor 接待餐飲",
"icon": "🍽️",
"date": "2026-01-15",
"item": "Food",
"spec": "—",
"qty": 1.0,
"unit": "—",
"supplier": "Chhne Meas",
"amount": 12.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Warp",
"sourceModule": "seed",
"dept": ""
},
{
"category": "guest",
"categoryLabel": "Guest / Auditor 接待餐飲",
"icon": "🍽️",
"date": "2026-01-15",
"item": "Food",
"spec": "—",
"qty": 1.0,
"unit": "—",
"supplier": "Chhne Meas",
"amount": 9.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Warp",
"sourceModule": "seed",
"dept": ""
},
{
"category": "guest",
"categoryLabel": "Guest / Auditor 接待餐飲",
"icon": "🍽️",
"date": "2026-01-15",
"item": "Food",
"spec": "—",
"qty": 1.0,
"unit": "—",
"supplier": "Chhne Meas",
"amount": 10.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Warp",
"sourceModule": "seed",
"dept": ""
},
{
"category": "guest",
"categoryLabel": "Guest / Auditor 接待餐飲",
"icon": "🍽️",
"date": "2026-01-15",
"item": "Food",
"spec": "—",
"qty": 1.0,
"unit": "—",
"supplier": "Chhne Meas",
"amount": 5.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Warp",
"sourceModule": "seed",
"dept": ""
},
{
"category": "guest",
"categoryLabel": "Guest / Auditor 接待餐飲",
"icon": "🍽️",
"date": "2026-02-05",
"item": "Tissue",
"spec": "—",
"qty": 1.0,
"unit": "—",
"supplier": "ABA Bank",
"amount": 2.6,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Customer",
"sourceModule": "seed",
"dept": ""
},
{
"category": "gas",
"categoryLabel": "Gas 煤氣",
"icon": "🔥",
"date": "2026-02-24",
"item": "LPG Gas 48kg",
"spec": "48kg/drum",
"qty": 1.0,
"unit": "drum",
"supplier": "KPS",
"amount": 45.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Kitchen",
"sourceModule": "seed",
"dept": ""
},
{
"category": "clinic",
"categoryLabel": "Clinic 診所藥費",
"icon": "🏥",
"date": "2026-02-01",
"item": "Medical form books",
"spec": "",
"qty": 40.0,
"unit": "book",
"supplier": "",
"amount": 50.0,
"consumption": 0.0,
"consUnit": "",
"purpose": "For Production Form 4501-8500",
"sourceModule": "seed",
"dept": ""
}
]
};
